name:                omise-hs-sample
version:             0.1.0.0
github:              "iporsut/omise-hs-sample"
author:              "Weerasak Chongnguluam"
maintainer:          "singpor@gmail.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iporsut/omise-hs-sample>

executables:
  omise-hs-sample-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - omise-hs
